server:
  port: 9350

logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.danawa.fastcatx: INFO
  file:
    name: output.log

elasticsearch:
  thread: 50
  username: fastcatx
  password: fastcatx
  connectionTimeout: 30000
  sockekTimeout: 300000
  nodes:
    - host: 192.168.1.123
      port: 9200
      scheme: http
    - host: 192.168.1.123
      port: 9200
      scheme: http
